name: Build and Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  release:
    types: [published]

permissions:
  contents: read

jobs:
  Windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Test with CMake
        run: |
          cmake -S . -B build
          cmake --build build --config Release --target tests
          ctest --verbose --test-dir build -C Release

  Ubuntu:
    strategy:
      matrix:
        runner: [ubuntu-latest, ubuntu-24.04-arm]
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install requirements
        run: |
          sudo apt install libgtest-dev cmake clang g++

      - name: Lightweight test with GCC
        run: CXX=g++ bash run_tests_unix.sh

      - name: Lightweight test with Clang
        run: CXX=clang++ bash run_tests_unix.sh

      - name: Test with CMake (-DSIMPLEINI_USE_SYSTEM_GTEST=OFF)
        run: |
          cmake -S . -B build -DSIMPLEINI_USE_SYSTEM_GTEST=OFF
          cmake --build build
          ctest --verbose --test-dir build

      - name: Test with CMake (-DSIMPLEINI_USE_SYSTEM_GTEST=ON)
        run: |
          cmake -S . -B build-system-gtest -DSIMPLEINI_USE_SYSTEM_GTEST=ON
          cmake --build build-system-gtest
          ctest --verbose --test-dir build-system-gtest

  MacOS:
    runs-on: macos-14
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install requirements
        run: |
          brew list googletest &>/dev/null || brew install googletest
          brew list cmake &>/dev/null || brew install cmake

      - name: Lightweight test with Clang
        run: CXX=clang++ bash run_tests_unix.sh

      - name: Test with CMake (-DSIMPLEINI_USE_SYSTEM_GTEST=OFF)
        run: |
          cmake -S . -B build -DSIMPLEINI_USE_SYSTEM_GTEST=OFF
          cmake --build build
          ctest --verbose --test-dir build

      - name: Test with CMake (-DSIMPLEINI_USE_SYSTEM_GTEST=ON)
        run: |
          cmake -S . -B build-system-gtest -DSIMPLEINI_USE_SYSTEM_GTEST=ON
          cmake --build build-system-gtest
          ctest --verbose --test-dir build-system-gtest
